<?php /*require('inc/config.php');
	  require('inc/funciones.php');
	  require('models/db/clsDatos.php'); */
		 ?>
<!DOCTYPE html>
<html class="lockscreen">
    <head>
        <meta charset="UTF-8">
        <title>504 - POS | Acceso</title>
        <meta charset="UTF-8">
	    <link href="assets/css/Irwin2382.css" rel="stylesheet">
	    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
	    <script src="assets/js/login.js"></script>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- bootstrap 3.0.2 -->
        <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="css/AdminLTE.css" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <script>function formulario(f) {
            if (f.username.value   == '') { alert ('El Nombre esta vacío'); 
            f.username.focus(); return false; }
            if (f.password.value  == '') { alert ('La Contraseña esta vacia');
            f.password.focus(); return false; } return true; }
        </script>
        
        <style type="text/css"> 
            #div_carga{
                position:absolute;
                top:0;
                left:0;
                width:100%;
                height:100%;
                    /*background: url(../../../img/fondo.png) repeat;*/
                    background: #007bb6 ;
                    opacity: 0.5; 
                    display: none;
                    z-index: 1;
            }

            #cargador{
                position:absolute;
                top:50%;
                left: 50%;
                margin-top: -25px;
                margin-left: -25px;
            }
        
        </style>
        
    </head>
    <body>
        <div id="div_carga">
            <img id="cargador" src="img/ajax-loader1.gif"/>
        </div>
        <!-- Automatic element centering using js -->
        <div class="center">            
            <div class="headline text-center" id="time">
                <!-- Time auto generated by js -->
            </div><!-- /.headline -->
            
            <!-- User name -->
            <div class="lockscreen-name" style="font-size:30px;font-family: 'Kaushan Script', cursive;">504 - POS</div>
            
            <!-- START LOCK SCREEN ITEM -->
            <div class="lockscreen-item" style=" width:500px">
                <!-- lockscreen image -->
               <!-- <div class="lockscreen-image">
                    <img src="img/avatar5.png" alt="user image"/>
                </div>-->
                <!-- /.lockscreen-image -->
				
                <!-- lockscreen credentials (contains the form) -->
                <div class="lockscreen-credentials" style=" width:700px">   
		<br>             
                    <div id="ver" style="width:20px; background-color:#000; display:none"></div>					                        <img src="img/ajax-loader.gif" style="width:20px; background-color:#000; display:none">               
		    <div class="input-group" >
                    <p id='alert_error' class='text-error visible'></p>
		    <p id='alert_success' class='text-correcto visible'></p>
                        <form id="LoginSimpleIrwin2382"  onsubmit="return formulario(this)">
                            <input type="text" id="username" class="form-control" style=" font-size:18px; font-weight:bold" placeholder="Usuario" autocomplete="off" ><br><br>
                            <input type="password" id="password" class="form-control" style=" font-size:18px; font-weight:bold" placeholder="Contraseña"><br><br>
                            <input type="submit" id="EnviarLogin" value="Iniciar Sesión" class="boton_2"><i class="fa fa-arrow-right text-muted"></i><input type="reset" class="boton_2" style="width:100px" value="Limpiar" /><br>
                            
			</form>
                    </div>
				
                </div><!-- /.lockscreen credentials -->
				
            </div><!-- /.lockscreen-item -->
				
            <div class="lockscreen-link">
                <a href="views/seguridad/v_registro.php">Registro</a>
            </div>            
        </div><!-- /.center -->

        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="js/bootstrap.min.js" type="text/javascript"></script>

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
                startTime();
                $(".center").center();
                $(window).resize(function() {
                    $(".center").center();
                });
            });

            /*  */
            function startTime()
            {
                var today = new Date();
                var h = today.getHours();
                var m = today.getMinutes();
                var s = today.getSeconds();

                // add a zero in front of numbers<10
                m = checkTime(m);
                s = checkTime(s);

                //Check for PM and AM
                var day_or_night = (h > 11) ? "PM" : "AM";

                //Convert to 12 hours system
                if (h > 12)
                    h -= 12;

                //Add time to the headline and update every 500 milliseconds
                $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
                setTimeout(function() {
                    startTime()
                }, 500);
            }

            function checkTime(i)
            {
                if (i < 10)
                {
                    i = "0" + i;
                }
                return i;
            }


            /* CENTER ELEMENTS IN THE SCREEN */
            jQuery.fn.center = function() {
                this.css("position", "absolute");
                this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                        $(window).scrollTop()) - 30 + "px");
                this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                        $(window).scrollLeft()) + "px");
                return this;
            }
        </script>
    </body>
</html>